services:
  - type: web
    name: institutional-tracker-web
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && pip install gunicorn"
    startCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
